# Generated by Django 3.1.3 on 2021-01-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0002_auto_20210108_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_added',
        ),
        migrations.AddField(
            model_name='product',
            name='shopping_list',
            field=models.ManyToManyField(to='shoppinglist.ShoppingList'),
        ),
        migrations.DeleteModel(
            name='ProductListTable',
        ),
    ]
