# Generated by Django 3.1.3 on 2021-01-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0004_dish_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='recipe',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
