# Generated by Django 3.1.3 on 2021-01-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0005_dish_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='link',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='time_of_day',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='season',
            field=models.CharField(default=None, max_length=6, null=True),
        ),
    ]
